<template>
  <NuxtLink
    class="
      group
      border
      rounded-full
      border-amethyst-300
      dark:border-amethyst-700
      bg-gradient-to-b
      from-amethyst-500 from-60%
      to-amethyst-100
      dark:from-amethyst-800
      dark:from-60%
      dark:to-amethyst-500
      dark:hover:from-amethyst-700
      dark:hover:from-60%
      dark:hover:to-amethyst-400
      hover:from-amethyst-600 hover:from-60% hover:to-amethyst-300
      relative
      px-4
      py-1
    "
  >
    <span
      class="
        z-[1]
        relative
        text-md
        font-semibold
        text-amethyst-800
        dark:text-white
        group-hover:text-amethyst-900 group-hover:dark:text-amethyst-100
      "
    >
      <slot></slot>
    </span>
    <div
      class="
        z-[0]
        w-[calc(100%-8px)]
        h-[calc(100%-8px)]
        rounded-full
        absolute
        inset-x-[4px]
        top-0
        bg-gradient-to-b
        from-white from-10%
        opacity-95
        dark:opacity-40
      "
    ></div>
  </NuxtLink>
</template>
